
version: '3'
services:
  bayes_topological_localiser:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    environment:
      - WEBSOCKET_URL=ws://car:8128/
    #command: ["python", "bayes_topological_localiser.py"]
    
  car:
    image: lcas.lincoln.ac.uk/lcas/car:latest
    env_file: ./env
    ports:
      - 8127
      - 8128
    environment:
      # We are tkaking the Google Maps API key form a .env file (or set it before docker-compose up)
      PYTHONUNBUFFERED: 1
      #GMAPS_API: ${GMAPS_API:-define_your_API_key_in_a_dot_env_file}
      #CAR_ROWS: ${CAR_ROWS:-1 2 3 4 5 6 7 8 9 10 11 12}
      #WEBSOCKET_URL: ${WEBSOCKET_URL:-wss://lcas.lincoln.ac.uk/rasberry/ws}
      CAR_LOG_DIR: "/tmp"

  nginx:
    image: nginx:latest
    ports:
      - 8827:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - car
    links:
      - car

  zenoh:
    image: eclipse/zenoh-bridge-ros2dds:latest
    environment:
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_DOMAIN_ID=0
      - ROS_DISTRO=humble
    ports:
      - 7447
      - 8888
    volumes:
      - ./cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro
    command: "-l tcp/0.0.0.0:7447 -r 0.0.0.0:8888 -d 0 -m peer"

  ros_bridge:
    build:
      context: .
      dockerfile: Dockerfile.ros_bridge
    environment:
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
      - ROS_DOMAIN_ID=0
      - ROS_MASTER_URI=http://localhost:11311
    user: ros
    volumes:
      - ./cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro
    command: "/bin/bash -c 'sleep 5; ros2 run ros1_bridge dynamic_bridge --bridge-all-topics'"
